vite change to api gateway
kerasus/soalaa pull request #1428
Opened 2023-05-27 10:32 UTC by Ayhanemoon

2023-05-27 11:26 UTC, kerasus requested changes

2023-05-27 11:26 UTC, kerasus commented on src/api/models/exam.js
> +        return response
normalize response

2023-05-27 11:26 UTC, kerasus commented on src/api/models/product.js
> +        sea: {
sea?

2023-05-27 11:26 UTC, kerasus commented on src/api/models/question.js
> +        return response.data.data
normalize response

2023-05-27 11:26 UTC, kerasus commented on src/components/Widgets/Quiz/Quiz.vue
> +          this.allExamsList = response.examList
don't use response

2023-05-28 11:40 UTC, Ayhanemoon commented on src/api/models/product.js
> +        sea: {
changed to landingAllProducts

2023-05-30 06:28 UTC, kerasus requested changes

2023-05-30 06:28 UTC, kerasus commented on src/api/models/question.js
> +        return response.data.data // List of Options Objects [{key,Value}]
create option model

{
    "id": "62f87df6e47ebedac3000d96",
    "type": "reference_type",
    "value": "کنکور",
    "image": null,
    "order": null,
    "updated_at": "2022-08-14 09:15:42",
    "created_at": "2022-08-14 09:15:42"
}

2023-05-30 10:03 UTC, Ayhanemoon commented on src/api/models/question.js
> +        return response.data.data // List of Options Objects [{key,Value}]
this options are not compatible with Option Model

2023-05-30 10:43 UTC, kerasus requested changes

2023-05-30 10:43 UTC, kerasus commented on src/api/models/exam.js
> +        return response.data.ranks
normalize response

2023-05-30 10:43 UTC, kerasus commented on src/api/models/exam.js
> +  userQuestionsWithAnswer(data = {}, cache) {
remove cache

2023-05-30 10:43 UTC, kerasus commented on src/api/models/exam.js
> +  userExamInfo(data = {}, cache) {
default cache

2023-05-30 10:43 UTC, kerasus commented on src/api/models/exam.js
>    getAllAnswerOfUser(userExamId, cache) {
default cache

2023-05-31 10:26 UTC, kerasus requested changes

2023-05-31 10:26 UTC, kerasus commented on src/api/models/exam.js
> +        return response.data.data // Exam Info
normalize response

2023-05-31 10:26 UTC, kerasus commented on src/api/models/exam.js
>          return response
normalize response

2023-05-31 10:26 UTC, kerasus commented on src/api/models/exam.js
>          return response
normalize response

2023-05-31 10:26 UTC, kerasus commented on src/api/models/exam.js
>          return response // String
normalize response

2023-05-31 10:26 UTC, kerasus commented on src/api/models/exam.js
> +        return response.data.ranks // String
normalize response

2023-05-31 10:26 UTC, kerasus commented on src/api/models/exam.js
> +        return response.data // object that contains main&sub_category&Zirgorooh
normalize response

2023-05-31 10:26 UTC, kerasus commented on src/api/models/exam.js
> +        return response.data // file list
normalize response

2023-06-11 09:47 UTC, kerasus requested changes

2023-06-11 09:47 UTC, kerasus commented on src/api/models/question.js
> +        return response.data
normalize response

2023-06-14 12:48 UTC, kerasus approved these changes

2023-06-14 12:48 UTC, merged